version: '2'
services:
  postgres:
    image: postgres

  telegraf:
    image: telegraf
    ports:
      - "8125:8125"
      - "8092:8092"
      - "8094:8094"

    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

    depends_on:
      - influxdb

  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"

    volumes:
      - ./influxdb.conf:/home/influxdb.conf
      - ./data:/var/lib/influxdb/data

    command: influxd -config /home/influxdb.conf

    depends_on:
      - chronograf
      - kapacitor

  chronograf:
    image: chronograf
    ports:
      - "10000:10000"

  kapacitor:
    image: kapacitor
    ports:
      - "9092:9092"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
